#!/usr/bin/env bash
# This line connects to the computer (172.17.15.83) using the "school" private key, without asking to confirm the connection
ssh -o StrictHostKeyChecking=no -i ~/.ssh/school ubuntu@54.89.196.80
