#!/usr/bin/env bash
# This line connects to the computer (127.0.0.1) using the "school" private key, without asking to confirm the connection.
ssh -i ~/.ssh/school -o StrictHostKeyChecking=no ubuntu@127.0.0.1
