#!/usr/bin/env bash

# Ensure .ssh directory exists
mkdir -p ~/.ssh

# Overwrite the existing key without prompt
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty" -y
echo "SSH key pair created successfully."
