#!/usr/bin/env bash
# Your SSH client configuration must be configured to use the private key `~/.ssh/school`
# Your SSH client configuration must be configured to refuse to authenticate using a password

Host 54.204.65.110
     PasswordAuthentication no
     IdentifyFile ~/.ssh/school
