#!/usr/bin/env bash
# a script to transfer a file from the client to the server

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path_to_file=$1
server_ip=$2
username=$3
ssh_key=$4

# Use SCP to transfer the file to the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$server_ip:~/"
