#!/usr/bin/env bash
# a ash script that transfers file from our clint to a server

if [ $# -lt 4 ]; then 
	echo "usage:0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_2file=$1
server_ip=$2
username=$3
ssh_key=$4

scp -o strictHostkeychecking=0 -i "ssh_key" "$path_2_file" $username"@"$server_ip":~/
